name:                           Docker Image Nightly Release

# Run "nightly" build on each commit to "dev" branch.
on:
  push:
    branches:
      - dev

jobs:
  deploy-docker:
    name:                       Build Release
    runs-on:                    ubuntu-latest
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@master
      - name:                   Install toolchain
        uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            1.52.1
          profile:              minimal
          override:             true
      - name:                   Deploy to docker hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: openethereum/openethereum
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: scripts/docker/alpine/Dockerfile
          tags: "nightly"
